[manifest]
version = "1.0.0"
priority = 4

[[patches]]
# this is very awesome jank that shouldnt break with updates adding newlines to the end anymore
[patches.copy]
target = '''=[SMODS cardpronouns "badge.lua"]'''
position = "append"
sources = [
    "lovely/pronounbadges.lua"
]

[[patches]]
[patches.regex]
target = '''=[SMODS cardpronouns "badge.lua"]'''
pattern = '''end\n+AAAAAAAAAAAAAAAAAAAAAAA'''
position = "at"
payload = ''
match_indent = false