[manifest]
version = "1.0.0"
priority = 4

[[patches]]
[patches.pattern]
target = '''=[SMODS cardpronouns "badge.lua"]'''
pattern = '''align = "cm",'''
position = "after"
payload = '''
ecatto_american = badge.key == "ecatto_eaglenoise_any",
'''
match_indent = true
times = 1